name: Build/Push WriteApis Container

on:
  push:
    branches: 
    - development
    paths:
    - 'ipaas-aks-apis/IssueWriteApis/**'

env:
  ACR_LOGIN_SERVER: ipaasacr.azurecr.io
  PACKAGE_PATH: 'ipaas-aks-apis/IssueWriteApis'
  DOTNET_VERSION: '5.0'
  image_name: 'ipaas-issue-writeapis'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.PACKAGE_PATH }}'
          dotnet restore
          popd

      - name: 'Publish Project to Output Directory'
        shell: bash
        run: |
          pushd './${{ env.PACKAGE_PATH }}'
          dotnet publish --configuration Release --output bin/publish
          popd
          
      - name: 'Login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.SPN_CLIENTID }}
          password: ${{ secrets.SPN_CLIENTSECRET }}

      - name: Push Container to ACR
        working-directory: ${{ env.PACKAGE_PATH }} 
        run: |
          docker build . -t ${{env.ACR_LOGIN_SERVER}}/${{env.image_name}}:${{ github.sha }}
          docker push ${{env.ACR_LOGIN_SERVER}}/${{env.image_name}}:${{ github.sha }}
